import Head from "next/head";
import { Inter } from "next/font/google";

import { Hero, Who, Works, Contact } from "@/components";
import styled from "@emotion/styled";

const bg = require("../../public/img/bg.jpeg");

const inter = Inter({ subsets: ["latin"] });

type BackgroundProps = {
  src: string;
};

const Container = styled.div<BackgroundProps>`
  height: 100vh;
  scroll-snap-type: y mandatory;
  scroll-behavior: smooth;
  overflow-y: auto;
  scrollbar-width: none;
  color: white;
  background: url(${({ src }) => src});
  &::-webkit-scrollbar {
    display: none;
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>3D-Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container src="/img/bg.jpeg">
        <Hero />
        <Who />
        <Works />
        <Contact />
      </Container>
    </>
  );
}
